language: node_js
node_js:
  - '8'
  - '10'
cache:
  directories:
    - "node_modules"
script:
  - npm run lint
  - npm test
  - npm run coveralls
deploy:
  provider: script
  skip_cleanup: true
  script:
    - npx semantic-release
